### ISSUE TITLE
Math Captcha

### ISSUE THREAD

**Issue by MarauderXtreme** [JustusAdam/vote-helper#1]
Today they introduced a Math Captcha. It is fairly easy to solve it. You just need to get a span with the class "captcha-formula". Take the string and erase the last 3 characters. ([:-3])
These are 2 spaces with a eqqulas sign in between. The rest is the equation.
Then you just need to set the result as value of the input with the class "captcha".
Have a look at this [bin](https://ghostbin.com/paste/q2r3a).

**Comment by MarauderXtreme** [comment]
Ah. I just saw that this Captcha is dynamically created via JavaScript. I'm too inexperienced in python to know how I get this to work.

**Comment by JustusAdam** [comment]
Do the votes fail?

**Comment by MarauderXtreme** [comment]
Okay. Never mind. The link exists. The Captcha just sets the css to display. _facepalm_
